# Generated by Django 4.1.7 on 2023-03-19 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0002_material_productmaterial_products_sales_salesitems_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
