# Generated by Django 4.1.7 on 2023-03-19 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0004_alter_customuser_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
