# Generated by Django 4.1.7 on 2023-03-19 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0006_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='bills',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='posApp.userinfo'),
        ),
    ]
