# Generated by Django 4.1.7 on 2023-03-20 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0008_alter_bills_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='status',
        ),
    ]
