# Generated by Django 4.1.7 on 2023-03-20 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0009_remove_userinfo_is_active_remove_userinfo_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='date_joined',
        ),
    ]
