# Generated by Django 4.1.7 on 2023-03-20 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0010_remove_userinfo_date_added_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='billItems',
        ),
    ]
