# Generated by Django 4.1.7 on 2023-03-20 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0011_delete_billitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='tablename',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
