# Generated by Django 4.1.7 on 2023-03-20 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0013_alter_sales_tablename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='tablename',
            field=models.CharField(max_length=100),
        ),
    ]
